/**
 * Las plantillas de rol del backend (`bamardev-backend/src/permisos/catalogo.ts`),
 * copiadas tal cual para armar sesiones de prueba con permisos reales. Si el
 * catálogo cambia, se regenera: es la fuente de verdad de los permisos que
 * manda el login (PLAN-ROLES-NEGOCIO §7: Encargado = SUPERVISOR, Cajero /
 * Dependiente / Vendedor / Recepción = CAJERO, y así).
 *
 * Sólo lo que la plantilla trae PRENDIDO (los ajustes apagados no viajan en el
 * login). `:PROPIO` = alcance "sólo lo suyo".
 */

/** La feature del plan que habilita cada permiso (null = núcleo, siempre). */
export const FEATURE_DE_PERMISO: Record<string, string | null> = {
  "ventas.vender": "pos",
  "ventas.historial": "pos",
  "ventas.anular": "pos",
  "ventas.ver_precios": null,
  "caja.operar": "caja",
  "caja.ver_todas": "caja",
  "caja.movimientos": "movimientos_caja",
  "qr.configurar": "pago_qr_mixto",
  "autorizar.pin": "autorizacion_pin",
  "credito.otorgar": "fiado",
  "credito.cobrar": "fiado",
  "credito.cobrar_sin_caja": "fiado",
  "credito.limite_editar": "fiado",
  "catalogo.ver": "catalogo",
  "catalogo.editar": "catalogo",
  "costos.ver": null,
  "inventario.mover": "inventario",
  "inventario.aprobar": "aprobacion_inventario",
  "almacenes.administrar": "inventario",
  "proveedores.gestionar": "inventario",
  "insumos.gestionar": "insumos",
  "dashboard.ver": "inventario",
  "reportes.ver": "reportes",
  "reportes.operacion": "reportes_operacion",
  "reportes.rentabilidad": "reportes_rentabilidad",
  "gastos.gestionar": "gastos",
  "usuarios.administrar": "usuarios",
  "negocio.configurar": null,
  "salon.atender": "salon",
  "salon.cobrar": "salon",
  "salon.cobrar_mesero": "mesero_cobra",
  "salon.administrar": "salon",
  "delivery.asignar": "delivery",
  "entregas.realizar": "delivery",
  "lotes.gestionar": "lotes",
  "controlados.libro": null,
  "encargos.gestionar": "encargos",
  "agenda.ver": "agenda",
  "agenda.gestionar": "agenda",
  "agenda.crear_propias": "agenda",
  "agenda.estado": "agenda",
  "agenda.sobreturno": "agenda",
  "agenda.bloquear": "agenda",
  "agenda.bloquear_propias": "agenda",
  "agenda.configurar": "agenda",
  "reservas.aprobar": "reserva_online",
  "cola.gestionar": "cola_walkin",
  "cliente.ver_ficha": "clientes",
  "cliente.editar": "clientes",
  "cliente.ver_telefono": null,
  "cliente.ver_salud": "clientes",
  "cliente.datos_personales": "clientes",
  "comisiones.ver": "comisiones",
  "comisiones.liquidar": "comisiones",
  "agenda.reportes": "agenda",
  "cliente.marketing": "clientes_retencion",
  "cliente.exportar": "clientes_retencion",
  "promociones.gestionar": "promociones",
  "vales.vender": "gift_cards",
  "vales.anular": "gift_cards",
  "propinas.ver": "propinas",
  "propinas.pagar": "propinas",
  "consumo.recetas": "consumo_servicio",
  "consumo.ajustar": "consumo_servicio",
  "fichatecnica.ver": "ficha_tecnica",
  "fichatecnica.editar": "ficha_tecnica",
  "cliente.editar_salud": "consentimientos",
  "personal.gestionar": "agenda",
};

export const PLANTILLAS = {
  ADMIN: [
    "ventas.vender",
    "ventas.historial",
    "ventas.anular",
    "ventas.ver_precios",
    "caja.operar",
    "caja.ver_todas",
    "caja.movimientos",
    "qr.configurar",
    "autorizar.pin",
    "credito.otorgar",
    "credito.cobrar",
    "credito.cobrar_sin_caja",
    "credito.limite_editar",
    "catalogo.ver",
    "catalogo.editar",
    "costos.ver",
    "inventario.mover",
    "inventario.aprobar",
    "almacenes.administrar",
    "proveedores.gestionar",
    "insumos.gestionar",
    "dashboard.ver",
    "reportes.ver",
    "reportes.operacion",
    "reportes.rentabilidad",
    "gastos.gestionar",
    "usuarios.administrar",
    "negocio.configurar",
    "salon.atender",
    "salon.cobrar",
    "salon.administrar",
    "delivery.asignar",
    "lotes.gestionar",
    "controlados.libro",
    "encargos.gestionar",
    "agenda.ver",
    "agenda.gestionar",
    "agenda.estado",
    "agenda.sobreturno",
    "agenda.bloquear",
    "agenda.configurar",
    "reservas.aprobar",
    "cola.gestionar",
    "cliente.ver_ficha",
    "cliente.editar",
    "cliente.ver_telefono",
    "cliente.ver_salud",
    "cliente.datos_personales",
    "comisiones.ver",
    "comisiones.liquidar",
    "agenda.reportes",
    "cliente.marketing",
    "cliente.exportar",
    "promociones.gestionar",
    "vales.vender",
    "vales.anular",
    "propinas.ver",
    "propinas.pagar",
    "consumo.recetas",
    "consumo.ajustar",
    "fichatecnica.ver",
    "fichatecnica.editar",
    "cliente.editar_salud",
    "personal.gestionar",
  ],
  SUPERVISOR: [
    "ventas.vender",
    "ventas.historial",
    "ventas.anular",
    "ventas.ver_precios",
    "caja.operar",
    "caja.ver_todas",
    "caja.movimientos",
    "qr.configurar",
    "autorizar.pin",
    "credito.otorgar",
    "credito.cobrar",
    "credito.limite_editar",
    "catalogo.ver",
    "costos.ver",
    "catalogo.editar",
    "inventario.mover",
    "inventario.aprobar",
    "almacenes.administrar",
    "proveedores.gestionar",
    "insumos.gestionar",
    "dashboard.ver",
    "lotes.gestionar",
    "controlados.libro",
    "reportes.ver",
    "reportes.operacion",
    "reportes.rentabilidad",
    "gastos.gestionar",
    "usuarios.administrar",
    "personal.gestionar",
    "salon.atender",
    "salon.cobrar",
    "salon.administrar",
    "delivery.asignar",
    "encargos.gestionar",
    "agenda.ver",
    "agenda.gestionar",
    "agenda.estado",
    "reservas.aprobar",
    "cola.gestionar",
    "cliente.ver_ficha",
    "cliente.editar",
    "cliente.ver_telefono",
    "cliente.ver_salud",
    "agenda.sobreturno",
    "agenda.bloquear",
    "agenda.configurar",
    "agenda.reportes",
    "comisiones.ver",
    "cliente.marketing",
    "vales.vender",
    "vales.anular",
    "propinas.ver",
    "propinas.pagar",
    "consumo.recetas",
    "consumo.ajustar",
    "fichatecnica.ver",
    "fichatecnica.editar",
  ],
  CAJERO: [
    "ventas.vender",
    "ventas.historial",
    "ventas.anular",
    "ventas.ver_precios",
    "caja.operar",
    "qr.configurar",
    "credito.otorgar",
    "credito.cobrar",
    "catalogo.ver",
    "salon.atender",
    "salon.cobrar",
    "delivery.asignar",
    "encargos.gestionar",
    "agenda.ver",
    "agenda.gestionar",
    "agenda.estado",
    "reservas.aprobar",
    "cola.gestionar",
    "cliente.ver_ficha",
    "cliente.editar",
    "cliente.ver_telefono",
    "cliente.ver_salud",
    "cliente.marketing",
    "vales.vender",
    "consumo.ajustar",
    "fichatecnica.ver",
    "fichatecnica.editar",
  ],
  MESERO: [
    "catalogo.ver",
    "ventas.ver_precios",
    "encargos.gestionar",
    "salon.atender:PROPIO",
    "salon.cobrar_mesero:PROPIO",
  ],
  REPARTIDOR: [
    "ventas.ver_precios",
    "entregas.realizar:PROPIO",
  ],
  PROFESIONAL: [
    "agenda.ver:PROPIO",
    "agenda.estado:PROPIO",
    "cliente.ver_ficha:PROPIO",
    "cliente.ver_salud:PROPIO",
    "cliente.editar_salud:PROPIO",
    "ventas.ver_precios",
    "comisiones.ver:PROPIO",
    "propinas.ver:PROPIO",
    "consumo.ajustar:PROPIO",
    "fichatecnica.ver:PROPIO",
    "fichatecnica.editar:PROPIO",
  ],
} as const;
